(require 'supergenpass)
(if
    (and
     (equal "oyMqrlvnf0" (sgp-generate "aZ6hsFkQAB" "facebook.com"))
     (equal "da9XVof7M0" (sgp-generate "fB0JxUJk3F" "cnn.com"))
     (equal "fGHiN8lZxx" (sgp-generate "fWeQm8cIm4" "slashdot.org"))
     (equal "sEhpjUR63S" (sgp-generate "fmXLipc0a9" "tumblr.com"))
     (equal "qRC0j8PWiG" (sgp-generate "fssqka0uhR" "twitter.com"))
     (equal "rKwJk8yOQG" (sgp-generate "et8U4PacDy" "twitter.com"))
     (equal "sw3dFkj12E" (sgp-generate "hUyoJKKb8X" "cnn.com"))
     (equal "xAYTxp2vDC" (sgp-generate "hxJch45dWd" "slashdot.org"))
     (equal "q3U0Svw2q4" (sgp-generate "iSRqWL1NIv" "tumblr.com"))
     (equal "d7mlILjHMJ" (sgp-generate "j4fdVHliBW" "twitter.com"))
     (equal "aptJNSF8VF" (sgp-generate "lonPN3Slmu" "cnn.com"))
     (equal "iDeDdndX2C" (sgp-generate "m0x8y8pQd0" "slashdot.org"))
     (equal "j7y4V48Gp6" (sgp-generate "oP9jePVJEt" "tumblr.com"))
     (equal "elghLVEnK9" (sgp-generate "odCS62yxVF" "twitter.com"))
     (equal "p1hfy8UK9C" (sgp-generate "pC37b4Ed8U" "cnn.com"))
     (equal "q9w1KwFirF" (sgp-generate "pLBe2YlyTe" "slashdot.org"))
     (equal "jhyc6nMIh8" (sgp-generate "qIW3jgzAVY" "tumblr.com"))
     (equal "iOqD952kBv" (sgp-generate "r04PRY4gAq" "twitter.com"))
     (equal "vJ02TX3P8F" (sgp-generate "rDL8WCOsmK" "cnn.com"))
     (equal "w9HCMcoIa2" (sgp-generate "sh8kMDPyhF" "slashdot.org"))
     (equal "w18AZ5n2ON" (sgp-generate "t8HQVPPSwA" "tumblr.com"))
     (equal "vaRgN0sbJd" (sgp-generate "tbUkLl20QC" "twitter.com"))
     (equal "akElMy91Rx" (sgp-generate "u2262a1TEg" "cnn.com"))
     (equal "uh3fW39Spg" (sgp-generate "unxdaQdxQ4" "slashdot.org"))
     (equal "w6bVgW3oC0" (sgp-generate "uvphI9ofTX" "tumblr.com"))
     (equal "p9PhTOC166" (sgp-generate "vGkM2qMik7" "twitter.com"))
     (equal "w8PV7d4x8L" (sgp-generate "vvdsM88uvl" "cnn.com"))
     (equal "ee9FRo8jZP" (sgp-generate "wHwt3lz6hr" "slashdot.org"))
     (equal "s999eW064I" (sgp-generate "wsjPWFc2wr" "tumblr.com"))
     (equal "d58WUKHzV3" (sgp-generate "wwV3EPLpJp" "twitter.com"))
     (equal "qZtt7qRlUm" (sgp-generate "xP9Ut9HIVB" "cnn.com"))
     (equal "hSsjnotX7B" (sgp-generate "xZj9ucltUq" "slashdot.org"))
     (equal "kRROFDvMs8" (sgp-generate "xwz5j3mnM1" "tumblr.com"))
     (equal "xwv9miGtrC" (sgp-generate "y5kDzKGHw5" "twitter.com"))
     (equal "bbQhkc0Pqh" (sgp-generate "y8h9oZquqc" "cnn.com"))
     (equal "ubRPZrdfu5" (sgp-generate "abcdefg" "cnn.com"))
     (equal "xaIlcL02A3" (sgp-generate "TheSeasonedSchemer" "slashdot.org"))
     (equal "xXuB5haYik" (sgp-generate "ColdAndFluRelief" "flowdock.com"))
     (equal "oZ8YbHxSKg" (sgp-generate "LiveLongAndProper" "lisp.org")))
    (message "All Passed")
  (message "Failures!"))
